Add tests and update Api wrapper
wegenerbenjamin/sepsesam pull request #16
Opened 2024-07-16 12:20 UTC by DerYannis1

add more tests and updated some functions of the api wrapper

2024-07-16 14:29 UTC, v411e commented on t/tests.py
> +
Please consider using a formatter like [Ruff](https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff) for auto-formatting. These line breaks are huuge :)

2024-07-16 14:52 UTC, v411e requested changes
Looks good, thanks a lot! I'd be glad if you could auto-format it before we merge it

2024-08-06 11:45 UTC, v411e commented on src/sepsesam/api.py
>          if "queryMode" in kwargs:
Is `queryMode` deprecated? If so, we can also delete these lines

2024-08-06 11:48 UTC, v411e commented on src/sepsesam/api.py
> +        log.debug("Running function")
This log is not very expressive

```suggestion
```

2024-08-06 12:15 UTC, v411e approved these changes

2024-08-20 09:30 UTC, DerYannis1 commented on src/sepsesam/api.py
>          if "queryMode" in kwargs:
It is deprecated and can be deleted.
```suggestion
       
```

2024-08-21 07:23 UTC, v411e commented on src/sepsesam/api.py
> +
Awesome!

2024-08-21 07:26 UTC, v411e commented on t/tests.py
> +        #self.assertTrue(len(api.command_event_find(**{"commandName": "eventCommand1"}))>1)
Does this work now? :)

2024-08-21 07:26 UTC, v411e commented on t/tests.py
> +        #len(api.command_event_find(**{"commandName": "eventCommand1"}))==1
Does this work now?

2024-08-21 12:38 UTC, v411e approved these changes

2024-08-21 13:16 UTC, merged